---
- name: Create documents
  ansible.windows.win_file:
    path: "{{ item.path }}"
    state: touch
  loop: "{{ vulnerable_windows_scenarios_documents }}"
  loop_control:
    label: "{{ item.path }}"
  when: ansible_os_family == "Windows"

- name: Set content of documents
  community.windows.win_lineinfile:
    path: "{{ item.path }}"
    line: "{{ item.content }}"
  loop: "{{ vulnerable_windows_scenarios_documents }}"
  loop_control:
    label: "{{ item.path }}"
  when: ansible_os_family == "Windows"

- name: Create and populate welcome document
  ansible.builtin.template:
    src: welcome.txt.j2
    dest: "{{ item.path }}"
    mode: '0644'
  loop: "{{ vulnerable_windows_scenarios_welcome_documents }}"
  loop_control:
    label: "{{ item.path }}"
  vars:
    user_name: "{{ item.user.name }}"
    user_password: "{{ item.user.password }}"
    user_manager: "{{ item.user.manager }}"
    user_mentor: "{{ item.user.mentor }}"
    share_name: "{{ item.share.name }}"
  when: ansible_os_family == "Windows"
