---
- name: Ensure directories for shares exist
  ansible.windows.win_file:
    path: "{{ item.path }}"
    state: directory
  loop: "{{ vulnerable_windows_scenarios_shares }}"
  loop_control:
    label: "{{ item.path }}"

- name: Create network shares
  ansible.windows.win_share:
    name: "{{ item.name }}"
    path: "{{ item.path }}"
    description: "{{ item.description }}"
    full_access: "{{ item.full_access }}"
  loop: "{{ vulnerable_windows_scenarios_shares }}"
  loop_control:
    label: "{{ item.name }}"
