---
- name: Clean up build dependencies and caches
  block:
    - name: Ensure Sliver binaries exist before cleanup
      ansible.builtin.stat:
        path: "{{ item }}"
      loop:
        - "{{ sliver_install_path }}/sliver-server"
        - "{{ sliver_install_path }}/sliver-client"
      register: sliver_binaries_check
      become: true

    - name: Verify all Sliver binaries exist
      ansible.builtin.assert:
        that:
          - item.stat.exists
        fail_msg: "Binary {{ item.item }} does not exist"
      loop: "{{ sliver_binaries_check.results }}"

    - name: Stop Sliver service before cleanup
      ansible.builtin.systemd:
        name: sliver
        state: stopped
      become: true
      when: sliver_setup_systemd | bool
      failed_when: false

    - name: Clean up Sliver source code and build artifacts
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        # Keep .git for idempotency with setup.yml
        - "{{ sliver_install_path }}/.github"
        - "{{ sliver_install_path }}/client"
        - "{{ sliver_install_path }}/server"
        - "{{ sliver_install_path }}/implant"
        - "{{ sliver_install_path }}/protobuf"
        - "{{ sliver_install_path }}/vendor"
        - "{{ sliver_install_path }}/go.mod"
        - "{{ sliver_install_path }}/go.sum"
        - "{{ sliver_install_path }}/Makefile"
        - "{{ sliver_install_path }}/Dockerfile"
        - "{{ sliver_install_path }}/.dockerignore"
        - "{{ sliver_install_path }}/.gitignore"
        - "{{ sliver_install_path }}/.tool-versions"
        - "{{ sliver_install_path }}/LICENSE"
        - "{{ sliver_install_path }}/README.md"
        - "{{ sliver_install_path }}/docs"
        - "{{ sliver_install_path }}/test"
        - "{{ sliver_install_path }}/util"
      become: true
      failed_when: false  # Some paths might not exist

    - name: Remove build-only packages for Debian-based systems
      ansible.builtin.apt:
        name: "{{ sliver_debian_build_packages }}"
        state: absent
        autoremove: true
        purge: true
      become: true
      when:
        - ansible_os_family == "Debian"
        - sliver_cleanup_remove_build_packages | bool

    - name: Remove ASDF and Go installation
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ sliver_user_home }}/.asdf"
        - "{{ sliver_user_home }}/go"
        - "{{ sliver_user_home }}/.cache/go-build"
      become: true
      when: sliver_cleanup_remove_golang | bool

    - name: Remove unused packages and dependencies for Debian-based systems
      ansible.builtin.apt:
        autoremove: true
        autoclean: true
      become: true
      when:
        - ansible_os_family == "Debian"
        - sliver_cleanup_package_cache | bool

    - name: Clean apt package cache for Debian-based systems
      ansible.builtin.apt:
        clean: true
      become: true
      when:
        - ansible_os_family == "Debian"
        - sliver_cleanup_package_cache | bool

    - name: Clean temporary files and user caches
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/tmp/sliver*"
        - "/var/tmp/sliver*"
        - "{{ sliver_user_home }}/.cache"
      become: true
      when: sliver_cleanup_temp_files | bool

    - name: Start Sliver service after cleanup
      ansible.builtin.systemd:
        name: sliver
        state: started
      become: true
      when: sliver_setup_systemd | bool

  rescue:
    - name: Cleanup failed - attempting to restore service
      ansible.builtin.systemd:
        name: sliver
        state: started
      become: true
      when: sliver_setup_systemd | bool
      failed_when: false

    - name: Report cleanup failure
      ansible.builtin.fail:
        msg: "Cleanup failed. Please check the system state."
