---
- name: Create Sliver users
  ansible.builtin.include_role:
    name: cowdogmoo.workstation.user_setup
  vars:
    user_setup_default_users: "{{ sliver_users }}"

- name: Check if .bash_profile exists for each sliver user
  ansible.builtin.stat:
    path: "/home/{{ item.username }}/.bash_profile"
  register: bash_profile_stat
  become: true
  become_user: "{{ item.username }}"
  loop: "{{ sliver_users }}"

- name: Ensure .bash_profile exists for each sliver user
  ansible.builtin.file:
    path: "/home/{{ item.username }}/.bash_profile"
    state: touch
    owner: "{{ item.username }}"
    group: "{{ item.usergroup }}"
    mode: '0644'
  become: true
  become_user: "{{ item.username }}"
  when: not bash_profile_stat.results | selectattr('invocation.module_args.path', 'equalto', '/home/' + item.username + '/.bash_profile') | map(attribute='stat.exists') | first | default(false)
  loop: "{{ sliver_users }}"

- name: Install required packages for Sliver
  ansible.builtin.include_role:
    name: cowdogmoo.workstation.package_management
  vars:
    package_management_common_install_packages: "{{ sliver_common_install_packages }}"
    package_management_debian_specific_packages: "{{ sliver_debian_packages }}"
    package_management_redhat_specific_packages: "{{ sliver_el_packages }}"

- name: Install asdf and go for sliver users
  ansible.builtin.include_role:
    name: cowdogmoo.workstation.asdf
  vars:
    asdf_users: "{{ sliver_users | list }}"

- name: Configure Git to allow sliver_install_path as a safe directory
  community.general.git_config:
    name: safe.directory
    scope: global
    value: "{{ sliver_install_path }}"
  become: true

- name: Clone Sliver repo
  ansible.builtin.git:
    repo: 'https://github.com/bishopfox/sliver.git'
    dest: "{{ sliver_install_path }}"
    version: master
  become: true

- name: Check current ownership of {{ sliver_install_path }}
  ansible.builtin.stat:
    path: "{{ sliver_install_path }}"
  register: sliver_stat
  become: true

- name: Add sliver_install_path to $PATH for each sliver user
  ansible.builtin.lineinfile:
    path: "/home/{{ item.username }}/.bash_profile"
    line: "export PATH=$PATH:{{ sliver_install_path }}"
    insertafter: EOF
    regexp: "^export PATH=.*:{{ sliver_install_path }}.*$"
  become: true
  become_user: "{{ item.username }}"
  loop: "{{ sliver_users }}"

- name: Set build user to the first sliver user with sudo privileges
  ansible.builtin.set_fact:
    build_user: "{{ sliver_users | selectattr('sudo', 'equalto', true) | first | default({'username': 'root'}) }}"

- name: Ensure correct ownership of the Sliver repository
  ansible.builtin.file:
    path: "{{ sliver_install_path }}"
    owner: sliver
    group: sliver
    recurse: true
  become: true
  when: sliver_stat.stat.pw_name != 'sliver' or sliver_stat.stat.gr_name != 'sliver'

- name: Check if Sliver server needs to be built
  ansible.builtin.stat:
    path: "{{ sliver_install_path }}/sliver-server"
  register: sliver_server_stat
  become: true
  changed_when: false

- name: Build Sliver as the build user
  ansible.builtin.command:
    cmd: gmake
    chdir: "{{ sliver_install_path }}"
  become: true
  become_user: "{{ build_user.username }}"
  environment:
    PATH: "/home/{{ build_user.username }}/.asdf/shims:{{ ansible_env.PATH }}"
  tags:
    - molecule-idempotence-notest
  changed_when: "'molecule-idempotence-notest' not in ansible_skip_tags"

- name: Check if Sliver server has been unpacked
  ansible.builtin.stat:
    path: "/home/{{ build_user.username }}/.sliver"
  register: sliver_server_unpacked_stat
  become: true
  changed_when: false

- name: Unpack Sliver server
  ansible.builtin.command:
    cmd: "{{ sliver_install_path }}/sliver-server unpack --force"
  become: true
  when: not sliver_server_unpacked_stat.stat.exists
  changed_when: "'Unpacking complete' in unpack_result.stdout"
  register: unpack_result

- name: Generate operator configs for each sliver user
  ansible.builtin.shell:
    cmd: |
      {{ sliver_install_path }}/sliver-server operator --name {{ item.username }} \
      --lhost localhost --save "{{ sliver_install_path }}/sliver-client/configs"
      chown -R {{ item.username }}:"{{ item.usergroup }}" "{{ sliver_install_path }}/sliver-client"
  become: true
  args:
    executable: /bin/bash
  changed_when: "'configs saved' in result.stdout"
  register: result
  loop: "{{ sliver_users }}"

- name: Include systemd tasks
  ansible.builtin.include_tasks: systemd.yml
  when: sliver_setup_systemd | bool
