---
- name: Install required packages for Sliver
  ansible.builtin.include_role:
    name: cowdogmoo.workstation.package_management
  vars:
    package_management_common_install_packages: "{{ sliver_common_install_packages }}"
    package_management_debian_specific_packages: "{{ sliver_debian_packages }}"
    package_management_redhat_specific_packages: "{{ sliver_el_packages }}"

- name: Create user
  ansible.builtin.include_role:
    name: cowdogmoo.workstation.user_setup
  vars:
    user_setup_default_users:
      - username: "{{ sliver_username }}"
        usergroup: "{{ sliver_usergroup }}"
        shell: "{{ sliver_shell }}"
        sudo: true

- name: Include sliver_get_user_home tasks
  ansible.builtin.include_tasks: sliver_get_user_home.yml

- name: Ensure home directory exists for sliver user
  ansible.builtin.file:
    path: "{{ sliver_user_home }}"
    state: directory
    owner: "{{ sliver_username }}"
    group: "{{ sliver_usergroup }}"
    mode: '0750'
  become: true

- name: Check if .bash_profile exists for sliver user
  ansible.builtin.stat:
    path: "{{ sliver_user_home }}/.bash_profile"
  register: bash_profile_stat
  become: true

- name: Ensure .bash_profile exists for sliver user
  ansible.builtin.file:
    path: "{{ sliver_user_home }}/.bash_profile"
    state: touch
    owner: "{{ sliver_username }}"
    group: "{{ sliver_usergroup }}"
    mode: '0644'
  become: true
  when: not bash_profile_stat.stat.exists

- name: Check if asdf is installed for sliver user
  ansible.builtin.stat:
    path: "{{ sliver_user_home }}/.asdf"
  register: asdf_installed

- name: Check if asdf binary is installed
  ansible.builtin.stat:
    path: "/usr/local/bin/asdf"
  register: asdf_binary_installed

- name: Install asdf and golang for sliver user
  ansible.builtin.include_role:
    name: cowdogmoo.workstation.asdf
  vars:
    asdf_username: "{{ sliver_username }}"
    asdf_usergroup: "{{ sliver_usergroup }}"
    asdf_shell: "{{ sliver_shell }}"
    asdf_plugins: "{{ sliver_asdf_plugins }}"
    asdf_user_home: "{{ sliver_user_home }}"
    asdf_data_dir: "{{ sliver_user_home }}/.asdf"
    asdf_bin_dir: "/usr/local/bin"
  when: not asdf_installed.stat.exists or not asdf_binary_installed.stat.exists

- name: Include Sliver setup tasks
  ansible.builtin.include_tasks: setup.yml

- name: Include systemd tasks
  ansible.builtin.include_tasks: systemd.yml
  when: sliver_setup_systemd | bool
