---
plugin: amazon.aws.aws_ec2
regions:
  - "{{ lookup('env', 'AWS_DEFAULT_REGION') | default('us-west-1', true) }}"
hostnames:
  - instance-id
  - tag:Name
filters:
  "tag:Name":
    - "packer-sliver"
keyed_groups:
  - key: tags.Name
    prefix: name_
compose:
  ansible_host: instance_id
  ansible_fqdn: public_dns_name
strict: true
