---
galaxy_info:
  role_name: logging
  author: Jayson Grace
  namespace: cowdogmoo
  description: Provides logging directories and log rotation for other roles.
  company: CowDogMoo
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Kali
      versions:
        - all
    - name: EL
      versions:
        - all
  galaxy_tags:
    - user
    - setup
dependencies: []
