---
namespace: l50
name: arsenal
version: "1.0.0"
readme: README.md
authors:
  - Jayson Grace <techvomit.net>
description: Install and configure offsec utilities and tooling that I employ regularly.
license_file: "LICENSE"
tags: [c2, linux, sliver, tools, offsec]
repository: https://github.com/l50/ansible-collection-arsenal
issues: https://github.com/l50/ansible-collection-arsenal
