---
roles:
  - name: l50.ansible_atomic_red_team
    src: https://github.com/l50/ansible-atomic-red-team

collections:
  - name: amazon.aws
    version: 8.2.0
  - name: ansible.windows
  - name: community.docker
  - name: community.general
  - name: community.windows
  - name: cowdogmoo.workstation
