---
roles:
  - name: l50.ansible_atomic_red_team
    src: https://github.com/l50/ansible-atomic-red-team

collections:
  - name: amazon.aws
    version: 9.2.0
  - name: ansible.windows
    version: 2.7.0
  - name: community.docker
    version: 4.4.0
  - name: community.general
    version: 10.3.1
  - name: cowdogmoo.workstation
    version: 2.0.3
