---
roles:
  - name: l50.ansible_atomic_red_team
    src: https://github.com/l50/ansible-atomic-red-team

collections:
  - name: amazon.aws
    version: 9.4.0
  - name: ansible.windows
    version: 2.8.0
  - name: community.docker
    version: 4.5.2
  - name: community.general
    version: 10.5.0
  - name: https://github.com/CowDogMoo/ansible-collection-workstation.git
    type: git
    version: main
