---
roles:
  - name: l50.ansible_atomic_red_team
    src: https://github.com/l50/ansible-atomic-red-team

collections:
  - name: amazon.aws
    version: 9.0.0
  - name: ansible.windows
    version: 2.5.0
  - name: community.docker
    version: 4.0.1
  - name: community.general
    version: 10.0.1
  - name: cowdogmoo.workstation
    version: 1.9.2
