---
roles:
  - name: l50.ansible_atomic_red_team
    src: https://github.com/l50/ansible-atomic-red-team

collections:
  - name: amazon.aws
    version: 10.1.2
  - name: ansible.windows
    version: 3.3.0
  - name: community.docker
    version: 5.0.3
  - name: community.general
    version: 12.0.1
  - name: https://github.com/CowDogMoo/ansible-collection-workstation.git
    type: git
    version: main
