---
version: "3"

includes:
  ansible: "https://raw.githubusercontent.com/CowDogMoo/taskfile-templates/main/ansible/Taskfile.yaml"
  github: "https://raw.githubusercontent.com/CowDogMoo/taskfile-templates/main/github/Taskfile.yaml"
  pre-commit: "https://raw.githubusercontent.com/CowDogMoo/taskfile-templates/main/pre-commit/Taskfile.yaml"
  renovate: "https://raw.githubusercontent.com/CowDogMoo/taskfile-templates/main/renovate/Taskfile.yaml"

tasks:
  default:
    desc: "Run all CI tasks"
    cmds:
      - task: ansible:lint-ansible
      - task: run-pre-commit
      - task: ansible:run-molecule-tests

  run-pre-commit:
    desc: "Update, clear cache, and run pre-commit hooks"
    cmds:
      - task: pre-commit:update-hooks
      - task: pre-commit:clear-cache
      - task: pre-commit:run-hooks
