---
version: "3"

includes:
  ansible: "https://raw.githubusercontent.com/CowDogMoo/taskfile-templates/main/ansible/Taskfile.yaml"
  github: "https://raw.githubusercontent.com/CowDogMoo/taskfile-templates/main/github/Taskfile.yaml"
  pre-commit: "https://raw.githubusercontent.com/CowDogMoo/taskfile-templates/main/pre-commit/Taskfile.yaml"
  renovate: "https://raw.githubusercontent.com/CowDogMoo/taskfile-templates/main/renovate/Taskfile.yaml"

tasks:
  default:
    desc: "Run all CI tasks"
    cmds:
      - task: ansible:lint-ansible
      - task: run-pre-commit
      - task: ansible:run-molecule-tests

  act:
    desc: "Run GitHub Actions molecule workflow using act"
    cmds:
      - |
        if [[ $(uname -s) == "Darwin" ]] && [[ $(uname -m) == "arm64" ]]; then
          act -W .github/workflows/molecule.yaml --container-architecture linux/arm64
        else
          act -W .github/workflows/molecule.yaml
        fi
    silent: true

  run-pre-commit:
    desc: "Update, clear cache, and run pre-commit hooks"
    cmds:
      - task: pre-commit:update-hooks
      - task: pre-commit:clear-cache
      - task: pre-commit:run-hooks

  gen-changelog:
    desc: "Generate the changelog for the next release"
    cmds:
      - |
        if [ -z "$NEXT_VERSION" ]; then
          echo "'NEXT_VERSION' environment variable not set. Example: NEXT_VERSION=1.0.0"
          exit 1
        fi
      - echo "Generating changelog for release $NEXT_VERSION"
      - task: ansible:changelog-lint
      - task: ansible:changelog-release
