---
- name: Ensure proper permissions for Mythic installation
  block:
    - name: Set ownership of Mythic directory
      ansible.builtin.file:
        path: "{{ mythic_install_dir }}"
        owner: "{{ mythic_user }}"
        group: "{{ mythic_user }}"
        recurse: yes
        mode: '0755'
      become: true

    - name: Ensure docker-compose.yml is writable
      ansible.builtin.file:
        path: "{{ mythic_install_dir }}/docker-compose.yml"
        mode: '0664'
        owner: "{{ mythic_user }}"
        group: "{{ mythic_user }}"
      become: true

- name: Install HTTP C2 profile
  block:
    - name: Start HTTP C2 installation
      ansible.builtin.command:
        cmd: "./mythic-cli install github https://github.com/MythicC2Profiles/http --force"
        chdir: "{{ mythic_install_dir }}"
      become: true
      become_user: "{{ mythic_user }}"
      register: mythic_http_install_start
      changed_when: mythic_http_install_start.rc != 0

    - name: Wait for HTTP container
      ansible.builtin.shell:
        cmd: "set -o pipefail && docker ps | grep http"
        executable: /bin/bash
      become: true
      register: mythic_http_check
      until: mythic_http_check.rc == 0
      retries: 30
      delay: 10
      changed_when: false

- name: Install Apollo agent
  block:
    - name: Start Apollo installation
      ansible.builtin.command:
        cmd: "./mythic-cli install github https://github.com/MythicAgents/apollo --force"
        chdir: "{{ mythic_install_dir }}"
      become: true
      become_user: "{{ mythic_user }}"
      register: mythic_apollo_install_start
      changed_when: mythic_apollo_install_start.rc != 0

    - name: Wait for Apollo container
      ansible.builtin.shell:
        cmd: "set -o pipefail && docker ps | grep apollo"
        executable: /bin/bash
      become: true
      register: mythic_apollo_check
      until: mythic_apollo_check.rc == 0
      retries: 30
      delay: 10
      changed_when: false

- name: Install Poseidon agent
  block:
    - name: Start Poseidon installation
      ansible.builtin.command:
        cmd: "./mythic-cli install github https://github.com/MythicAgents/poseidon --force"
        chdir: "{{ mythic_install_dir }}"
      become: true
      become_user: "{{ mythic_user }}"
      register: mythic_poseidon_install_start
      changed_when: mythic_poseidon_install_start.rc != 0

    - name: Wait for Poseidon container
      ansible.builtin.shell:
        cmd: "set -o pipefail && docker ps | grep poseidon"
        executable: /bin/bash
      become: true
      register: mythic_poseidon_check
      until: mythic_poseidon_check.rc == 0
      retries: 30
      delay: 10
      changed_when: false

- name: Install Mythic Forge
  block:
    - name: Start Mythic Forge installation
      ansible.builtin.command:
        cmd: "./mythic-cli install github https://github.com/MythicAgents/forge --force"
        chdir: "{{ mythic_install_dir }}"
      become: true
      become_user: "{{ mythic_user }}"
      register: mythic_forge_install_start
      changed_when: mythic_forge_install_start.rc != 0

    - name: Wait for Forge container
      ansible.builtin.shell:
        cmd: "set -o pipefail && docker ps | grep forge"
        executable: /bin/bash
      become: true
      register: mythic_forge_check
      until: mythic_forge_check.rc == 0
      retries: 30
      delay: 10
      changed_when: false

- name: Install Bloodhound agent
  block:
    - name: Start Bloodhound installation
      ansible.builtin.command:
        cmd: "./mythic-cli install github https://github.com/MythicAgents/bloodhound --force"
        chdir: "{{ mythic_install_dir }}"
      become: true
      become_user: "{{ mythic_user }}"
      register: mythic_bloodhound_install_start
      changed_when: mythic_bloodhound_install_start.rc != 0

    - name: Wait for Bloodhound container
      ansible.builtin.shell:
        cmd: "set -o pipefail && docker ps | grep bloodhound"
        executable: /bin/bash
      become: true
      register: mythic_bloodhound_check
      until: mythic_bloodhound_check.rc == 0
      retries: 30
      delay: 10
      changed_when: false
