---
- name: Include user setup tasks
  ansible.builtin.import_tasks: user.yml

- name: Include package installation tasks
  ansible.builtin.import_tasks: packages.yml

- name: Include Docker installation tasks
  ansible.builtin.import_tasks: docker.yml

- name: Include Mythic installation tasks
  ansible.builtin.import_tasks: mythic.yml

- name: Include Mythic agents tasks
  ansible.builtin.import_tasks: agents.yml

- name: Include Mythic service tasks
  ansible.builtin.import_tasks: service.yml
  when: mythic_setup_systemd | bool
