---
- name: Install required packages for ttpforge
  ansible.builtin.include_role:
    name: cowdogmoo.workstation.package_management
  vars:
    package_management_common_install_packages: "{{ ttpforge_common_install_packages }}"

- name: Check if .bash_profile exists for ttpforge user
  ansible.builtin.stat:
    path: "/home/{{ ttpforge_username }}/.bash_profile"
  register: bash_profile_stat
  become: true
  become_user: "{{ ttpforge_username }}"

- name: Ensure .bash_profile exists for ttpforge user
  ansible.builtin.file:
    path: "/home/{{ ttpforge_username }}/.bash_profile"
    state: touch
    owner: "{{ ttpforge_username }}"
    group: "{{ ttpforge_usergroup }}"
    mode: '0644'
  become: true
  become_user: "{{ ttpforge_username }}"
  # Only create if it does not exist already
  when: not bash_profile_stat.stat.exists

- name: Check if asdf is installed for ttpforge user
  ansible.builtin.stat:
    path: "/home/{{ ttpforge_username }}/.asdf"
  register: asdf_installed

- name: Install asdf (and go) for ttpforge user
  ansible.builtin.include_role:
    name: cowdogmoo.workstation.asdf
  vars:
    asdf_username: "{{ ttpforge_username }}"
    asdf_usergroup: "{{ ttpforge_usergroup }}"
    asdf_shell: "{{ ttpforge_shell }}"
    asdf_plugins: "{{ ttpforge_asdf_plugins }}"
    asdf_user_home: "/home/{{ ttpforge_username }}"
    asdf_dir: "/home/{{ ttpforge_username }}/.asdf"
  when: not asdf_installed.stat.exists

- name: Include TTPForge setup tasks
  ansible.builtin.include_tasks: setup.yml
