---
- name: Install required packages for ttpforge
  ansible.builtin.include_role:
    name: cowdogmoo.workstation.package_management
  vars:
    package_management_common_install_packages: "{{ ttpforge_common_install_packages }}"

- name: Check if .bash_profile exists for each ttpforge user
  ansible.builtin.stat:
    path: "/home/{{ item.username }}/.bash_profile"
  register: bash_profile_stat
  become: true
  become_user: "{{ item.username }}"
  loop: "{{ ttpforge_users }}"

- name: Ensure .bash_profile exists for each ttpforge user
  ansible.builtin.file:
    path: "/home/{{ item.username }}/.bash_profile"
    state: touch
    owner: "{{ item.username }}"
    group: "{{ item.usergroup }}"
    mode: '0644'
  become: true
  become_user: "{{ item.username }}"
  when: not bash_profile_stat.results | selectattr('invocation.module_args.path', 'equalto', '/home/' + item.username + '/.bash_profile') | map(attribute='stat.exists') | first | default(false)
  loop: "{{ ttpforge_users }}"

- name: Check if asdf is installed
  ansible.builtin.stat:
    path: "/home/{{ ttpforge_users[0].username }}/.asdf"
  register: asdf_installed

- name: Install asdf and go for ttpforge users
  ansible.builtin.include_role:
    name: cowdogmoo.workstation.asdf
  vars:
    asdf_username: "{{ ttpforge_users[0].username }}"
    asdf_usergroup: "{{ ttpforge_users[0].usergroup }}"
    asdf_shell: "{{ ttpforge_users[0].shell }}"
    asdf_plugins: "{{ ttpforge_users[0].asdf_plugins }}"
    asdf_user_home: "/home/{{ ttpforge_users[0].username }}"
    asdf_dir: "/home/{{ ttpforge_users[0].username }}/.asdf"
  when: not asdf_installed.stat.exists

- name: Include TTPForge setup tasks
  ansible.builtin.include_tasks: setup.yml
