---
- name: Define user-specific ttpforge installation path
  ansible.builtin.set_fact:
    ttpforge_install_path: "/home/{{ item.username }}/.local/bin/ttpforge"
  loop: "{{ ttpforge_users }}"
  when: item.username != 'root'

- name: Define root-specific ttpforge installation path
  ansible.builtin.set_fact:
    ttpforge_install_path: "/usr/local/bin/ttpforge"
  when: item.username == 'root'
  loop: "{{ ttpforge_users }}"

- name: Set global Go path for ttpforge
  ansible.builtin.set_fact:
    ttpforge_go_path: "/opt/asdf/shims/go"
  when: ttpforge_global_install

- name: Set user-specific Go path for ttpforge
  ansible.builtin.set_fact:
    ttpforge_go_path: "/home/{{ item.username }}/.asdf/shims/go"
  loop: "{{ ttpforge_users }}"
  when: not ttpforge_global_install

- name: Install required packages for ttpforge
  ansible.builtin.include_role:
    name: cowdogmoo.workstation.package_management
  vars:
    package_management_common_install_packages: "{{ ttpforge_common_install_packages }}"
    package_management_debian_specific_packages: "{{ ttpforge_debian_packages }}"
    package_management_redhat_specific_packages: "{{ ttpforge_el_packages }}"

- name: Configure Git to allow ttpforge repository as a safe directory
  community.general.git_config:
    name: safe.directory
    scope: global
    value: "{{ ttpforge_repo_path }}"
  when: ttpforge_global_install

- name: Clone ttpforge repo
  ansible.builtin.git:
    repo: 'https://github.com/facebookincubator/ttpforge.git'
    dest: "{{ ttpforge_repo_path }}"
    version: main
  become: true
  when: ttpforge_global_install

- name: Clone ttpforge repo for each specified user
  ansible.builtin.git:
    repo: 'https://github.com/facebookincubator/ttpforge.git'
    dest: "/home/{{ item.username }}/ttpforge"
    version: main
  become: true
  become_user: "{{ item.username }}"
  loop: "{{ ttpforge_users }}"
  when: not ttpforge_global_install

- name: Debug output for user-specific paths
  ansible.builtin.debug:
    msg: "Installing for user {{ item.username }} in path /home/{{ item.username }}/ttpforge"
  loop: "{{ ttpforge_users }}"

- name: Ensure correct ownership of ttpforge repository
  ansible.builtin.file:
    path: "/home/{{ item.username }}/ttpforge"
    owner: "{{ item.username }}"
    group: "{{ item.usergroup }}"
    recurse: true
  become: true
  changed_when: false
  loop: "{{ ttpforge_users }}"
  when: not ttpforge_global_install

- name: Check if ttpforge needs to be compiled for each user
  ansible.builtin.stat:
    path: "{{ item.install_path | default(ttpforge_install_path) }}"
  register: ttpforge_compiled
  become: true
  become_user: "{{ item.username }}"
  loop: "{{ ttpforge_users }}"
  when: not ttpforge_global_install

- name: Compile ttpforge for each user
  ansible.builtin.shell:
    cmd: |
      {{ ttpforge_go_path }} build -buildvcs=false -o {{ item.item.install_path | default(ttpforge_install_path) }}
    chdir: "{{ item.item.repo_path | default('/home/' ~ item.item.username ~ '/ttpforge') }}"
    executable: "{{ item.item.shell }}"
  become: true
  become_user: "{{ item.item.username }}"
  loop: "{{ ttpforge_compiled.results }}"
  when:
    - not ttpforge_global_install
    - not item.stat.exists
  tags:
    - molecule-idempotence-notest
  changed_when: "'molecule-idempotence-notest' not in ansible_skip_tags"

- name: Check if ttpforge has been initialized for each user
  ansible.builtin.stat:
    path: "/home/{{ item.username }}/.ttpforge"
  register: ttpforge_unpacked_stat_result
  changed_when: false
  become: true
  become_user: "{{ item.username }}"
  loop: "{{ ttpforge_users }}"
  when: not ttpforge_global_install

- name: Update user PATH in dotfile
  ansible.builtin.lineinfile:
    path: "/home/{{ item.username }}/{{ (item.shell == '/bin/zsh' and '.zshrc') or '.bashrc' }}"
    line: 'export PATH=$HOME/.local/bin:$PATH'
    owner: "{{ item.username }}"
    group: "{{ item.usergroup }}"
    mode: '0644'
    state: present
    create: true
  loop: "{{ ttpforge_users }}"
  when:
    - not ttpforge_global_install
    - item.shell in ['/bin/bash', '/bin/zsh']
  become: true
  become_user: "{{ item.username }}"

- name: Set ttpforge_unpacked_stat for each user
  ansible.builtin.set_fact:
    ttpforge_unpacked_stat: "{{ ttpforge_unpacked_stat | default({}) | combine({item.item.username: item.stat.exists}) }}"
  loop: "{{ ttpforge_unpacked_stat_result.results }}"
  when: not ttpforge_global_install

- name: Initialize ttpforge for each user
  ansible.builtin.command:
    cmd: "{{ ttpforge_install_path }} init"
  when:
    - not ttpforge_global_install
    - ttpforge_unpacked_stat[item.username] is defined
    - not ttpforge_unpacked_stat[item.username]
  become: true
  become_user: "{{ item.username }}"
  loop: "{{ ttpforge_users }}"
  register: unpack_result
  changed_when: "'TTPForge Initialized' in unpack_result.stdout"
