---
- name: Set ttpforge user home directory
  ansible.builtin.include_tasks: ttpforge_get_user_home.yml

- name: Install required packages for ttpforge
  ansible.builtin.include_role:
    name: cowdogmoo.workstation.package_management
  vars:
    package_management_common_install_packages: "{{ ttpforge_common_install_packages }}"

- name: Ensure home directory exists for ttpforge user
  ansible.builtin.file:
    path: "{{ ttpforge_user_home }}"
    state: directory
    owner: "{{ ttpforge_username }}"
    group: "{{ ttpforge_usergroup }}"
    mode: '0750'
  become: true

- name: Check if .bashrc exists for ttpforge user
  ansible.builtin.stat:
    path: "{{ ttpforge_user_home }}/.bashrc"
  register: bashrc_stat
  become: true

- name: Ensure .bashrc exists for ttpforge user
  ansible.builtin.file:
    path: "{{ ttpforge_user_home }}/.bashrc"
    state: touch
    owner: "{{ ttpforge_username }}"
    group: "{{ ttpforge_usergroup }}"
    mode: '0644'
  become: true
  when: not bashrc_stat.stat.exists

- name: Check if asdf is installed for ttpforge user
  ansible.builtin.stat:
    path: "{{ ttpforge_user_home }}/.asdf"
  register: asdf_installed

- name: Check if asdf binary is installed
  ansible.builtin.stat:
    path: "/usr/local/bin/asdf"
  register: asdf_binary_installed

- name: Install asdf and associated plugins for ttpforge user
  ansible.builtin.include_role:
    name: cowdogmoo.workstation.asdf
  vars:
    asdf_username: "{{ ttpforge_username }}"
    asdf_usergroup: "{{ ttpforge_usergroup }}"
    asdf_shell: "{{ ttpforge_shell }}"
    asdf_plugins: "{{ ttpforge_asdf_plugins }}"
    asdf_user_home: "{{ ttpforge_user_home }}"
    asdf_data_dir: "{{ ttpforge_user_home }}/.asdf"
    asdf_bin_dir: "/usr/local/bin"
  when: not asdf_installed.stat.exists or not asdf_binary_installed.stat.exists

- name: Include TTPForge setup tasks
  ansible.builtin.include_tasks: setup.yml
