---
galaxy_info:
  role_name: asdf
  namespace: cowdogmoo
  author: Jayson Grace
  description: Install asdf
  company: CowDogMoo
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: macOS
      versions:
        - all
    - name: EL
      versions:
        - all
  galaxy_tags:
    - asdf

dependencies:
  - role: cowdogmoo.workstation.package_management
