---
- name: Converge
  hosts: all
  gather_facts: true
  tasks:
    - name: Include default variables
      ansible.builtin.include_vars:
        file: "../../defaults/main.yml"

    - name: Include role under test
      ansible.builtin.include_role:
        name: l50.arsenal.coercion_tools
      vars:
        coercion_tools_pip_break_system_packages: true
