---
- name: Apply Vulnerable Windows Scenarios Role
  hosts: "{{ target | default('all') }}"
  vars_files:
    - ../../roles/vulnerable-windows-scenarios/vars/main.yml
  vars:
    ansible_connection: aws_ssm
    ansible_shell_type: powershell
  roles:
    - role: vulnerable-windows-scenarios
