---
- name: Vulnerable Windows Scenarios
  hosts: all
  tasks:
    - name: Generate random password for PaigeTurner
      ansible.builtin.set_fact:
        # TODO: Fix this
        # scenarios_paige_turner_password: "{{ lookup('community.general.password', '/dev/null length=16 chars=ascii_letters') }}"
        scenarios_paige_turner_password: "sup3rs3cure123!!!"
      when: ansible_os_family == "Windows"

    - name: Create local user PaigeTurner with random password
      ansible.windows.win_user:
        name: "PaigeTurner"
        password: "{{ scenarios_paige_turner_password }}"
        description: "New User"
        groups: []
      when: ansible_os_family == "Windows"

    - name: Ensure the Resources directory exists
      ansible.windows.win_file:
        path: C:\Resources
        state: directory
      when: ansible_os_family == "Windows"

    - name: Create the sensitive document in Resources
      ansible.windows.win_file:
        path: C:\Resources\attorney_client_privileged_intellectual_property.txt
        state: touch
      when: ansible_os_family == "Windows"

    - name: Set content of the sensitive document
      community.windows.win_lineinfile:
        path: C:\Resources\attorney_client_privileged_intellectual_property.txt
        line: "this is secret do not share with anyone 4f67650d0f81f138ba00675ea26cc9a4"
      when: ansible_os_family == "Windows"

    - name: Create the network share for Resources
      ansible.windows.win_share:
        name: DATABOX
        path: C:\Resources
        description: Resources Share
        full_access:
          - "PaigeTurner"
      when: ansible_os_family == "Windows"

    - name: Display PaigeTurner's password
      ansible.builtin.debug:
        msg: "PaigeTurner's password is {{ scenarios_paige_turner_password }}"
      when: ansible_os_family == "Windows"

    - name: Set crummy password for Frank Furter
      ansible.builtin.set_fact:
        scenarios_frank_furter_password: "Password123!"

    - name: Create local user FrankFurter with weak password
      ansible.windows.win_user:
        name: "FrankFurter"
        password: "{{ scenarios_frank_furter_password }}"
        description: "Description of the user"
        groups: []
      when: ansible_os_family == "Windows"

    - name: Ensure the DeptFiles directory exists
      ansible.windows.win_file:
        path: C:\DeptFiles
        state: directory
      when: ansible_os_family == "Windows"

    - name: Create the network share for DeptFiles
      ansible.windows.win_share:
        name: FSERVER01
        path: C:\DeptFiles
        description: Department Files Share
        full_access:
          - Everyone
      when: ansible_os_family == "Windows"

    - name: Create the welcome document in created DeptFiles file
      ansible.windows.win_file:
        path: C:\DeptFiles\Welcome.txt
        state: touch
      when: ansible_os_family == "Windows"

    - name: Populate the DeptFiles welcome document with content
      community.windows.win_lineinfile:
        path: C:\DeptFiles\Welcome.txt
        line: |
          Welcome aboard, Paige Turner!

          Your account details:
          Username: PaigeTurner
          Temp password: (set by IT Support, contact them for it, please change upon first login!!!)

          Important resources:
          - Employee handbook: \\DATABOX\Resources\
          - IT Support: x1234 or itsupport@
          - HR portal: http://intern/hr

          Your team:
          Manager: Frank
          Mentor: Sarah

          First week checklist:
          1. Set up workstation
          2. Complete new hire paperwork
          3. Attend orientation (Tues, 9 AM, Room 305)
          4. Schedule 1:1 with your manager
          5. Review Q3_Planning folder

          Don't forget to check out our Cake_Budget share for office snack info!

          Welcome to the team!
      when: ansible_os_family == "Windows"
