---
- name: Atomic Red Team
  hosts: all
  roles:
    - name: Create Atomic Red Team role user (if not already present)
      role: cowdogmoo.workstation.user_setup

    - name: Install Atomic Red Team
      role: l50.ansible_atomic_red_team
