# defaults/main.yml
---
ttpforge_install_path: /opt/ttpforge
ttpforge_users:
  - username: "{{ ansible_user_id | default(ansible_user, true) | default('ttpforge') }}"
    usergroup: "{{ (ansible_facts['os_family'] == 'Darwin') | ternary('staff', asdf_username | default('ttpforge')) }}"
    shell: zsh
    sudo: true
    asdf_plugins:
      - name: golang
        version: "1.23.5"
        scope: global
      - name: python
        version: "3.13.1"
        scope: global
