---
ttpforge_cleanup: false  # Enable for Docker/container builds to minimize image size
ttpforge_install_path: /opt/ttpforge
ttpforge_username: "{{
  ansible_facts['user_id']
  if ansible_facts['os_family'] == 'Darwin'
  else ansible_facts['distribution'] | lower }}"
ttpforge_usergroup: "{{
  'staff'
  if ansible_facts['os_family'] == 'Darwin'
  else ansible_facts['user_id']
  if ansible_facts['os_family'] in ['Debian', 'RedHat']
  else ansible_facts['distribution'] | lower }}"
ttpforge_shell: "{{
  '/bin/zsh' if ansible_facts['os_family'] == 'Darwin' else '/bin/bash' }}"
ttpforge_mise_plugins:
  # renovate: datasource=github-tags depName=golang packageName=golang/go extractVersion=^go(?<version>.*)$
  - name: go
    version: "1.26.5"
    scope: "global"
  # renovate: datasource=github-tags depName=python packageName=python/cpython extractVersion=^v(?<version>.*)$
  - name: python
    version: "3.14.6"
    scope: "global"
