---
# Path to the ttpforge repository (defaults to a globally accessible path)
ttpforge_repo_path: /opt/ttpforge

# Install ttpforge for all users on the system (this is for a system-wide install)
ttpforge_global_install: false

# Default users to install ttpforge for (modify as needed for a per-user install)
ttpforge_users:
  - username: "{{ ansible_env.USER if ansible_distribution == 'MacOSX' else ansible_distribution | lower }}"
    usergroup: "{{ 'staff' if ansible_distribution == 'MacOSX' else ansible_distribution | lower }}"
    sudo: true
    shell: /bin/bash
    plugins:
      - name: golang
        version: "1.22.1"
        scope: "global"
