---
ttpforge_install_path: /opt/ttpforge
ttpforge_username: "{% if ansible_os_family == 'Darwin' %}{{ ansible_user_id }}{% else %}{{ ansible_distribution | lower }}{% endif %}"
ttpforge_usergroup: "{% if ansible_os_family == 'Darwin' %}staff{% elif ansible_os_family == 'Debian' %}{{ ansible_user_id }}{% elif ansible_os_family == 'RedHat' %}{{ ansible_user_id }}{% else %}{{ ansible_distribution | lower }}{% endif %}"
ttpforge_shell: "{% if ansible_os_family == 'Darwin' %}/bin/zsh{% else %}/bin/bash{% endif %}"
ttpforge_asdf_plugins:
  # renovate: datasource=github-tags depName=golang packageName=golang/go extractVersion=^go(?<version>.*)$
  - name: golang
    version: "1.24.0"
    scope: "global"
  # renovate: datasource=github-tags depName=python packageName=python/cpython extractVersion=^v(?<version>.*)$
  - name: python
    version: "3.13.1"
    scope: "global"
