---
galaxy_info:
  role_name: vulnerable_windows_scenarios
  namespace: l50
  author: Jayson Grace
  description: |
    Scenarios is a collection of vulnerable windows scenarios for use in training
    and testing of cybersecurity tools and techniques.
  company: techvomit
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: macOS
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Windows
      versions:
        - all
  galaxy_tags:
    - purpleteam
    - offsec
