---
# Use Ansible Galaxy to install dependencies
dependency:
  name: galaxy

# Run molecule inside of a docker container
driver:
  name: docker

platforms:
  - name: ubuntu_user_setup
    image: "geerlingguy/docker-ubuntu2204-ansible:latest"
    # Setting the command to this is necessary for systemd containers
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true

  - name: kali_user_setup
    image: cisagov/docker-kali-ansible:latest
    # Setting the command to this is necessary for systemd containers
    command: ""
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true

provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}

verifier:
  name: ansible
