---
- name: Converge
  hosts: all
  gather_facts: true
  tasks:
    - name: Include default variables
      ansible.builtin.include_vars:
        file: "../../defaults/main.yml"

    - name: Include role under test
      ansible.builtin.include_role:
        name: l50.arsenal.lateral_movement_tools
