---
galaxy_info:
  role_name: sliver
  namespace: l50
  author: Jayson Grace
  description: Install sliver c2
  company: techvomit
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: macOS
      versions:
        - all
    - name: EL
      versions:
        - all
  galaxy_tags:
    - c2
    - offsec
dependencies:
  - role: cowdogmoo.workstation.package_management
  - role: cowdogmoo.workstation.asdf
