---
- name: Workstation
  hosts: all
  roles:
    - name: Setup users on workstation
      role: cowdogmoo.workstation.user_setup
      # For debugging
      # role: ../../roles/user_setup

    - name: Setup ZSH Configuration
      role: cowdogmoo.workstation.zsh_setup
      # For debugging
      # role: ../../roles/zsh_setup

    - name: Setup ASDF Configuration
      role: cowdogmoo.workstation.asdf
