---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  become: true

- name: Restart mythic services
  ansible.builtin.systemd:
    name: mythic
    state: restarted
  become: true
