---
- name: Converge
  hosts: all
  gather_facts: true

  roles:
    - role: l50.arsenal.sliver
      vars:
        sliver_mise_plugins:
          - name: go
            version: "1.24.0"
            scope: "global"
