---
- name: Converge
  hosts: all
  vars:
    test_username: "sliver"
    test_usergroup: "{{ sliver_username }}"
    test_shell: "/bin/bash"
  tasks:
    - name: Include default variables
      ansible.builtin.include_vars:
        file: "../../defaults/main.yml"

    - name: Include variables
      ansible.builtin.include_vars:
        file: "../../vars/main.yml"

    - name: Include role under test
      ansible.builtin.include_role:
        name: l50.arsenal.sliver
      vars:
        sliver_users:
          - username: "{{ test_username }}"
            usergroup: "{{ test_usergroup }}"
            shell: "{{ test_shell }}"
            sudo: false
            asdf_plugins:
              - name: golang
                version: "1.23.5"
                scope: global
