---
- name: Converge
  hosts: all
  tasks:
    - name: Include default variables
      ansible.builtin.include_vars:
        file: "../../defaults/main.yml"
    - name: Include variables
      ansible.builtin.include_vars:
        file: "../../vars/main.yml"
  roles:
    - name: Run the sliver role
      role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
