---
- name: Converge
  hosts: all
  gather_facts: true
  vars:
    sliver_username: "sliver"
    sliver_usergroup: "sliver"
    sliver_shell: "/bin/bash"

  roles:
    - role: l50.arsenal.sliver
      vars:
        sliver_asdf_plugins:
          - name: golang
            version: "1.24.0"
            scope: "global"
