---
- name: Converge
  hosts: all
  vars:
    container_user: "sliver"
    container_home: "/home/{{ container_user }}"
    sliver_default_username: "{{ container_user }}"
    sliver_default_group: "{{ container_user }}"
  tasks:
    - name: Include default variables
      ansible.builtin.include_vars:
        file: "../../defaults/main.yml"

    - name: Include variables
      ansible.builtin.include_vars:
        file: "../../vars/main.yml"

    - name: Include role under test
      ansible.builtin.include_role:
        name: l50.arsenal.sliver
      vars:
        sliver_users:
          - username: "{{ container_user }}"
            usergroup: "{{ container_user }}"
            shell: "/bin/bash"
            sudo: false
            asdf_plugins:
              - name: golang
                version: "1.23.5"
                scope: global
