---
- name: Verify
  hosts: all
  gather_facts: true
  vars:
    ttpforge_go_path: /opt/asdf/shims/go
    ttpforge_install_path: /usr/local/bin/ttpforge
    ttpforge_repo_path: /opt/ttpforge
    ttpforge_users:
      - username: "{{ ansible_env.USER if ansible_distribution == 'MacOSX' else ansible_distribution | lower }}"
        usergroup: "{{ 'staff' if ansible_distribution == 'MacOSX' else ansible_distribution | lower }}"
        shell: "/bin/bash"
        sudo: true
        plugins:
          - name: golang
            version: "1.22.1"
            scope: "global"

  tasks:
    - name: Check if ttpforge is installed
      ansible.builtin.stat:
        path: "{{ ttpforge_install_path }}"
      register: ttpforge

    - name: Debug ttpforge installation
      ansible.builtin.debug:
        msg: "TTPForge path: {{ ttpforge_install_path }}, exists: {{ ttpforge.stat.exists }}"

    - name: Assert that ttpforge is installed
      ansible.builtin.assert:
        that:
          - ttpforge.stat.exists

    - name: Check if ttpforge is initialized
      ansible.builtin.stat:
        path: "/home/{{ ttpforge_users[0].username }}/.ttpforge"
      register: forgeinit

    - name: Assert that ttpforge has been initialized
      ansible.builtin.assert:
        that:
          - forgeinit.stat.isdir is defined
          - forgeinit.stat.isdir
