---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Include default variables
      ansible.builtin.include_vars:
        file: "../../defaults/main.yml"

    - name: Check if TTPForge binary exists and is executable
      ansible.builtin.stat:
        path: "{{ ttpforge_install_path }}/ttpforge"
      register: ttpforge_binary

    - name: Check users exist
      ansible.builtin.command: "id -un {{ item.username }}"
      register: user_check
      changed_when: false
      failed_when: user_check.rc != 0
      loop: "{{ ttpforge_users }}"

    - name: Check user sudo access
      ansible.builtin.stat:
        path: "/etc/sudoers.d/{{ item.username }}"
      loop: "{{ ttpforge_users }}"
      register: sudoers_check
      failed_when: >
        sudoers_check.stat.exists == false and
        (item.sudo | bool) == true and
        item.username != 'root'
