- name: Verify TTPForge Setup
  hosts: all
  tasks:
    - name: Include default variables
      ansible.builtin.include_vars:
        file: "../../defaults/main.yml"

    - name: Print the PATH for each user
      ansible.builtin.shell:
        cmd: echo $PATH
      register: user_path
      become: true
      become_user: "{{ item.username }}"
      loop: "{{ ttpforge_users }}"
      changed_when: false

    - name: Output the PATH for each user
      ansible.builtin.debug:
        msg: "User: {{ item.item.username }}, PATH: {{ item.stdout }}"
      loop: "{{ user_path.results }}"

    - name: Define user-specific ttpforge installation path
      ansible.builtin.set_fact:
        ttpforge_install_path: "/home/{{ item.username }}/.local/bin/ttpforge"
      loop: "{{ ttpforge_users }}"
      when: item.username != 'root'

    - name: Check if ttpforge is installed for each user
      ansible.builtin.stat:
        path: "{{ ttpforge_install_path }}"
      register: ttpforge_stat
      become: true
      become_user: "{{ item.username }}"
      loop: "{{ ttpforge_users }}"

    - name: Assert that ttpforge is installed correctly
      ansible.builtin.assert:
        that:
          - item.stat.exists
        fail_msg: "TTPForge is not installed correctly for user {{ item.item.username }}"
        success_msg: "TTPForge is installed correctly for user {{ item.item.username }}"
      loop: "{{ ttpforge_stat.results }}"
